//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supershop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local); Initial Catalog=APOSDB; User ID=sa;Password=sapass123!;")]
        public string APOSSQLConnectionString {
            get {
                return ((string)(this["APOSSQLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=E:\\Data_laptop_1\\D_drive\\G_Drive\\Files_1\\dotproject\\supershop\\up_to_d" +
            "ate\\POS_4_1_3_1_Resource\\CodeC_File_advance_pos\\Adv_POS_6_1\\POS_Adv_Project_8_1\\" +
            "POS_Source_Code\\POS__SQLite\\supershop\\bin\\x86\\Debug\\psodb.db;version=3;new=False" +
            ";compress=True")]
        public string psodbConnectionString {
            get {
                return ((string)(this["psodbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=psodb.db;Version=3;New=False;Compress=True")]
        public string psodbConnectionString1 {
            get {
                return ((string)(this["psodbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=E:\\Data_laptop_1\\D_drive\\G_Drive\\Files_1\\dotproject\\supershop\\up_to_d" +
            "ate\\POS_4_1_3_1_Resource\\CodeC_File_advance_pos\\Adv_POS_6_1\\POS_Adv_Project_8_1\\" +
            "POS_Source_Code\\POS__SQLite\\supershop\\bin\\x86\\Debug\\psodb.db")]
        public string psodbConnectionString2 {
            get {
                return ((string)(this["psodbConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost; database=aposmysqldb; uid=root; PASSWORD=1234")]
        public string AposMysqlConnectionString {
            get {
                return ((string)(this["AposMysqlConnectionString"]));
            }
        }
    }
}
